FROM keltecc/nsjail:latest

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get install -y python3.8 python3.8-distutils python3-pip
# cal
RUN apt-get install -y bsdmainutils 

ENV PYTHONUNBUFFERED 1

WORKDIR /chroot/
COPY ./app/ ./app/
WORKDIR ./app/

RUN apt-get install -y curl
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.8 get-pip.py
RUN python3.8 -m pip install -r requirements.txt

WORKDIR /chroot/

RUN mkdir -p ./usr/lib/ && \
    cp -R /lib* . && \
    cp -R /usr/lib* ./usr/ && \
    mkdir -p ./usr/local/lib && \
    cp -R /usr/local/lib/python* ./usr/local/lib

RUN mkdir ./dev && \
    mknod ./dev/null c 1 3 && \
    mknod ./dev/zero c 1 5 && \
    mknod ./dev/random c 1 8 && \
    mknod ./dev/urandom c 1 9 && \
    chmod 666 ./dev/*

RUN mkdir -p ./bin/ && \
    cp /bin/sh \
       /bin/ls \
       /bin/cat \
       /bin/pwd \
       /bin/date \
       /bin/echo \
       ./bin/ && \
    ln -s /bin/sh ./bin/bash && \
    chmod 111 ./bin/*

RUN mkdir -p ./usr/bin/ && \
    cp /usr/bin/id \
       /usr/bin/whoami \
       /usr/bin/python3 \
       /usr/bin/uptime \
       /usr/bin/cal \
       /usr/bin/env \
       ./usr/bin/ && \
    chmod 111 ./usr/bin/*

RUN mkdir ./etc/ && \
    cp /etc/passwd ./etc/ && \
    chmod 444 ./etc/*

RUN mkdir ./tmp/ && \
    chmod 777 ./tmp/ && \
    chmod +t ./tmp/

WORKDIR /
ADD nsjail/nsjail.sh /nsjail.sh
RUN chmod 555 /nsjail.sh

WORKDIR /chroot/app/

RUN chmod 444 ./flag.txt

RUN touch ./rm_me.txt

#ENTRYPOINT ["/nsjail.sh" ]
#CMD [ "which", "cat"]
#WORKDIR /app/
#CMD [ "/usr/bin/python3", "server.py" ]

#ENV FLASK_APP=server.py
#ENV FLASK_ENV=development
#CMD [ "gunicorn", "-b", "0.0.0.0:5656", "-w", "4", "wsgi:app" ]
CMD [ "python3.8", "server.py"]
