/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _IO_FILE ;
enum _1_pr0c_$op ;
union _1_pr0c_$node ;
struct timeval ;
void syms_i$nit(void) ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int getpagesize() ;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern unsigned int strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
void numsLength_i$nit(void) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
void __attribute__((__optimize__(3)))  pr0c(void) ;
extern int printf(char const   * __restrict  __format  , ...) ;
void __attribute__((__optimize__(3)))  printPrize(char a ) ;
int _global_argc  =    0;
int nums[305] ;
extern int pthread_cond_signal(int *cond ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
extern int raise(int sig ) ;
char **_global_envp  =    (char **)0;
union _1_pr0c_$node {
   char _char ;
   unsigned int _unsigned_int ;
   unsigned char _unsigned_char ;
   long _long ;
   unsigned long _unsigned_long ;
   void *_void_star ;
   unsigned short _unsigned_short ;
   unsigned long long _unsigned_long_long ;
   signed char _signed_char ;
   long long _long_long ;
   int _int ;
   short _short ;
};
extern int unlink(char const   *filename ) ;
void printTurn(void) ;
unsigned int r4nd0m(unsigned int prev ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
void prizeLength_i$nit(void) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void abort() ;
extern void free(void *ptr ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
extern void exit(int status ) ;
extern void signal(int sig , void *func ) ;
void xorKey_i$nit(void) ;
typedef struct _IO_FILE FILE;
extern int close(int filedes ) ;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
void seed_i$nit(void) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
enum _1_pr0c_$op {
    _1_pr0c__Div_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 191,
    _1_pr0c__global$result_STA_0$value_LIT_0 = 190,
    _1_pr0c__branchIfTrue$expr_STA_0$label_LAB_0 = 253,
    _1_pr0c__call$func_LIT_0 = 64,
    _1_pr0c__constant_void_star$result_STA_0$value_LIT_0 = 24,
    _1_pr0c__convert_char2int$left_STA_0$result_STA_0 = 250,
    _1_pr0c__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 42,
    _1_pr0c__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 136,
    _1_pr0c__Eq_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 254,
    _1_pr0c__load_int$left_STA_0$result_STA_0 = 123,
    _1_pr0c__store_void_star$left_STA_0$right_STA_1 = 1,
    _1_pr0c__convert_int2char$left_STA_0$result_STA_0 = 182,
    _1_pr0c__constant_unsigned_long$result_STA_0$value_LIT_0 = 168,
    _1_pr0c__returnVoid$ = 90,
    _1_pr0c__store_int$left_STA_0$right_STA_1 = 163,
    _1_pr0c__string$result_STA_0$value_LIT_0 = 3,
    _1_pr0c__constant_int$result_STA_0$value_LIT_0 = 7,
    _1_pr0c__BXor_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 18,
    _1_pr0c__PlusPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1 = 154,
    _1_pr0c__convert_void_star2void_star$left_STA_0$result_STA_0 = 103,
    _1_pr0c__MinusA_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 197,
    _1_pr0c__convert_int2unsigned_long$left_STA_0$result_STA_0 = 35,
    _1_pr0c__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 58,
    _1_pr0c__goto$label_LAB_0 = 91,
    _1_pr0c__local$result_STA_0$value_LIT_0 = 100,
    _1_pr0c__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1 = 132
} ;
extern double ceil(double x ) ;
unsigned char _1_pr0c_$array[1][319]  = { {        _1_pr0c__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__local$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_pr0c__store_int$left_STA_0$right_STA_1,        _1_pr0c__global$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_pr0c__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_pr0c__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_pr0c__constant_void_star$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_pr0c__PlusPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_pr0c__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_pr0c__load_int$left_STA_0$result_STA_0,        _1_pr0c__local$result_STA_0$value_LIT_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_pr0c__store_int$left_STA_0$right_STA_1,        _1_pr0c__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_pr0c__local$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_pr0c__store_int$left_STA_0$right_STA_1, 
            _1_pr0c__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__global$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_pr0c__load_int$left_STA_0$result_STA_0,        _1_pr0c__local$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_pr0c__load_int$left_STA_0$result_STA_0,        _1_pr0c__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_pr0c__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_pr0c__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_pr0c__goto$label_LAB_0,        (unsigned char)203,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_pr0c__load_int$left_STA_0$result_STA_0,        _1_pr0c__local$result_STA_0$value_LIT_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_pr0c__load_int$left_STA_0$result_STA_0,        _1_pr0c__Eq_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_pr0c__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_pr0c__goto$label_LAB_0, 
            (unsigned char)152,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_pr0c__string$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_pr0c__local$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_pr0c__store_void_star$left_STA_0$right_STA_1, 
            _1_pr0c__constant_int$result_STA_0$value_LIT_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__global$result_STA_0$value_LIT_0,        (unsigned char)2,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_pr0c__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_pr0c__local$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_pr0c__load_int$left_STA_0$result_STA_0,        _1_pr0c__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_pr0c__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_pr0c__constant_void_star$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_pr0c__PlusPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_pr0c__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_pr0c__load_int$left_STA_0$result_STA_0,        _1_pr0c__Div_int_int2int$left_STA_0$result_STA_0$right_STA_1, 
            _1_pr0c__constant_int$result_STA_0$value_LIT_0,        (unsigned char)20,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__MinusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_pr0c__global$result_STA_0$value_LIT_0,        (unsigned char)3, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_pr0c__load_int$left_STA_0$result_STA_0, 
            _1_pr0c__BXor_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_pr0c__convert_int2char$left_STA_0$result_STA_0,        _1_pr0c__convert_char2int$left_STA_0$result_STA_0,        _1_pr0c__local$result_STA_0$value_LIT_0, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_pr0c__store_int$left_STA_0$right_STA_1,        _1_pr0c__call$func_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_pr0c__local$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_pr0c__load_int$left_STA_0$result_STA_0, 
            _1_pr0c__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_pr0c__local$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_pr0c__store_int$left_STA_0$right_STA_1, 
            _1_pr0c__local$result_STA_0$value_LIT_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__load_int$left_STA_0$result_STA_0,        _1_pr0c__global$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_pr0c__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_pr0c__local$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__load_int$left_STA_0$result_STA_0,        _1_pr0c__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_pr0c__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_pr0c__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__PlusPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_pr0c__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_pr0c__load_int$left_STA_0$result_STA_0, 
            _1_pr0c__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_pr0c__local$result_STA_0$value_LIT_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_pr0c__store_int$left_STA_0$right_STA_1,        _1_pr0c__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_pr0c__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__load_int$left_STA_0$result_STA_0,        _1_pr0c__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_pr0c__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1, 
            _1_pr0c__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__store_int$left_STA_0$right_STA_1,        _1_pr0c__goto$label_LAB_0,        (unsigned char)38, 
            (unsigned char)255,        (unsigned char)255,        (unsigned char)255,        _1_pr0c__goto$label_LAB_0, 
            (unsigned char)33,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            _1_pr0c__string$result_STA_0$value_LIT_0,        (unsigned char)3,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_pr0c__local$result_STA_0$value_LIT_0,        (unsigned char)32, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_pr0c__store_void_star$left_STA_0$right_STA_1, 
            _1_pr0c__call$func_LIT_0,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_pr0c__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_pr0c__returnVoid$}};
unsigned int seed ;
typedef unsigned long size_t;
int prizeLength ;
void nums_i$nit(void) ;
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
int m0n3y ;
int syms[61] ;
extern void perror(char const   *str ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
char prize_encoded[204] ;
char const   *_1_pr0c_$strings  =    "%c\000\n\000";
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
void m0n3y_i$nit(void) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
int numsLength ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long clock(void) ;
void gameRun(void) ;
extern long time(long *tloc ) ;
void prize_encoded_i$nit(void) ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern int rand() ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern int strcmp(char const   *a , char const   *b ) ;
int xorKey ;
extern double sqrt(double x ) ;
extern void *malloc(unsigned int size ) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int atoi(char const   *s ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
void printBanner(void) ;
void megaInit(void) ;
void nums_i$nit(void) 
{ 


  {
  nums[0] = 256816;
  nums[1] = 256752;
  nums[2] = 256724;
  nums[3] = 256740;
  nums[4] = 256728;
  nums[5] = 257084;
  nums[6] = 256780;
  nums[7] = 257100;
  nums[8] = 256756;
  nums[9] = 256808;
  nums[10] = 256836;
  nums[11] = 256832;
  nums[12] = 256660;
  nums[13] = 256804;
  nums[14] = 257096;
  nums[15] = 256760;
  nums[16] = 256820;
  nums[17] = 256812;
  nums[18] = 257100;
  nums[19] = 256760;
  nums[20] = 256796;
  nums[21] = 257076;
  nums[22] = 256660;
  nums[23] = 256768;
  nums[24] = 256728;
  nums[25] = 256764;
  nums[26] = 256732;
  nums[27] = 256828;
  nums[28] = 256844;
  nums[29] = 256804;
  nums[30] = 256820;
  nums[31] = 257084;
  nums[32] = 256832;
  nums[33] = 257076;
  nums[34] = 256828;
  nums[35] = 256720;
  nums[36] = 256660;
  nums[37] = 257084;
  nums[38] = 257092;
  nums[39] = 256828;
  nums[40] = 257092;
  nums[41] = 256752;
  nums[42] = 256836;
  nums[43] = 256732;
  nums[44] = 257096;
  nums[45] = 256660;
  nums[46] = 256808;
  nums[47] = 256812;
  nums[48] = 256728;
  nums[49] = 257100;
  nums[50] = 256824;
  nums[51] = 256740;
  nums[52] = 256844;
  nums[53] = 256740;
  nums[54] = 257092;
  nums[55] = 256796;
  nums[56] = 256660;
  nums[57] = 256844;
  nums[58] = 257080;
  nums[59] = 257100;
  nums[60] = 256740;
  nums[61] = 256720;
  nums[62] = 256660;
  nums[63] = 256812;
  nums[64] = 256824;
  nums[65] = 257100;
  nums[66] = 256828;
  nums[67] = 256820;
  nums[68] = 257064;
  nums[69] = 256780;
  nums[70] = 256832;
  nums[71] = 256988;
  nums[72] = 257080;
  nums[73] = 256780;
  nums[74] = 256768;
  nums[75] = 256736;
  nums[76] = 256772;
  nums[77] = 256724;
  nums[78] = 257080;
  nums[79] = 256824;
  nums[80] = 256832;
  nums[81] = 257080;
  nums[82] = 256772;
  nums[83] = 257076;
  nums[84] = 256816;
  nums[85] = 256660;
  nums[86] = 256728;
  nums[87] = 256832;
  nums[88] = 256756;
  nums[89] = 256832;
  nums[90] = 256724;
  nums[91] = 256740;
  nums[92] = 256828;
  nums[93] = 256720;
  nums[94] = 256740;
  nums[95] = 256732;
  nums[96] = 256660;
  nums[97] = 257100;
  nums[98] = 256724;
  nums[99] = 257096;
  nums[100] = 256836;
  nums[101] = 256768;
  nums[102] = 256752;
  nums[103] = 256836;
  nums[104] = 257092;
  nums[105] = 256804;
  nums[106] = 256844;
  nums[107] = 256660;
  nums[108] = 256768;
  nums[109] = 256780;
  nums[110] = 256836;
  nums[111] = 256748;
  nums[112] = 256824;
  nums[113] = 257080;
  nums[114] = 257092;
  nums[115] = 256760;
  nums[116] = 256820;
  nums[117] = 256660;
  nums[118] = 256740;
  nums[119] = 257080;
  nums[120] = 257084;
  nums[121] = 256760;
  nums[122] = 256736;
  nums[123] = 257076;
  nums[124] = 256736;
  nums[125] = 256772;
  nums[126] = 256836;
  nums[127] = 257076;
  nums[128] = 257092;
  nums[129] = 256728;
  nums[130] = 256732;
  nums[131] = 256728;
  nums[132] = 256840;
  nums[133] = 256780;
  nums[134] = 256732;
  nums[135] = 257076;
  nums[136] = 256764;
  nums[137] = 256728;
  nums[138] = 256724;
  nums[139] = 257084;
  nums[140] = 256824;
  nums[141] = 256760;
  nums[142] = 256844;
  nums[143] = 256984;
  nums[144] = 256832;
  nums[145] = 256736;
  nums[146] = 256660;
  nums[147] = 256756;
  nums[148] = 256804;
  nums[149] = 256844;
  nums[150] = 256744;
  nums[151] = 256660;
  nums[152] = 256828;
  nums[153] = 256780;
  nums[154] = 256732;
  nums[155] = 256744;
  nums[156] = 257044;
  nums[157] = 256796;
  nums[158] = 256756;
  nums[159] = 256828;
  nums[160] = 256804;
  nums[161] = 256804;
  nums[162] = 256748;
  nums[163] = 256820;
  nums[164] = 256844;
  nums[165] = 256816;
  nums[166] = 256808;
  nums[167] = 257080;
  nums[168] = 256820;
  nums[169] = 256812;
  nums[170] = 256756;
  nums[171] = 256840;
  nums[172] = 256748;
  nums[173] = 256840;
  nums[174] = 256748;
  nums[175] = 256780;
  nums[176] = 256816;
  nums[177] = 256756;
  nums[178] = 256736;
  nums[179] = 256752;
  nums[180] = 256812;
  nums[181] = 256728;
  nums[182] = 256720;
  nums[183] = 256808;
  nums[184] = 256840;
  nums[185] = 256752;
  nums[186] = 256812;
  nums[187] = 257100;
  nums[188] = 256816;
  nums[189] = 256740;
  nums[190] = 257100;
  nums[191] = 256752;
  nums[192] = 256724;
  nums[193] = 256720;
  nums[194] = 256812;
  nums[195] = 256732;
  nums[196] = 256816;
  nums[197] = 256732;
  nums[198] = 256768;
  nums[199] = 256840;
  nums[200] = 256844;
  nums[201] = 257096;
  nums[202] = 256728;
  nums[203] = 256824;
  nums[204] = 256660;
  nums[205] = 256740;
  nums[206] = 256812;
  nums[207] = 256804;
  nums[208] = 256800;
  nums[209] = 257100;
  nums[210] = 256760;
  nums[211] = 257080;
  nums[212] = 256752;
  nums[213] = 257084;
  nums[214] = 256744;
  nums[215] = 256768;
  nums[216] = 256824;
  nums[217] = 256756;
  nums[218] = 256836;
  nums[219] = 256756;
  nums[220] = 256800;
  nums[221] = 256756;
  nums[222] = 256796;
  nums[223] = 256780;
  nums[224] = 256824;
  nums[225] = 256744;
  nums[226] = 256768;
  nums[227] = 256760;
  nums[228] = 256816;
  nums[229] = 256780;
  nums[230] = 256744;
  nums[231] = 256844;
  nums[232] = 257080;
  nums[233] = 256828;
  nums[234] = 257084;
  nums[235] = 256804;
  nums[236] = 256744;
  nums[237] = 256724;
  nums[238] = 256720;
  nums[239] = 256836;
  nums[240] = 257084;
  nums[241] = 257080;
  nums[242] = 256728;
  nums[243] = 256748;
  nums[244] = 256744;
  nums[245] = 256740;
  nums[246] = 256844;
  nums[247] = 256740;
  nums[248] = 256824;
  nums[249] = 257084;
  nums[250] = 257080;
  nums[251] = 256764;
  nums[252] = 257100;
  nums[253] = 256728;
  nums[254] = 256732;
  nums[255] = 257096;
  nums[256] = 256768;
  nums[257] = 256756;
  nums[258] = 256820;
  nums[259] = 256744;
  nums[260] = 256720;
  nums[261] = 256780;
  nums[262] = 256772;
  nums[263] = 256820;
  nums[264] = 256760;
  nums[265] = 256796;
  nums[266] = 256828;
  nums[267] = 256736;
  nums[268] = 256744;
  nums[269] = 256816;
  nums[270] = 256836;
  nums[271] = 256752;
  nums[272] = 256760;
  nums[273] = 256732;
  nums[274] = 257100;
  nums[275] = 256844;
  nums[276] = 256756;
  nums[277] = 256760;
  nums[278] = 256744;
  nums[279] = 256828;
  nums[280] = 256728;
  nums[281] = 256820;
  nums[282] = 256840;
  nums[283] = 256828;
  nums[284] = 256836;
  nums[285] = 256744;
  nums[286] = 256748;
  nums[287] = 256796;
  nums[288] = 257092;
  nums[289] = 257084;
  nums[290] = 256752;
  nums[291] = 256824;
  nums[292] = 256800;
  nums[293] = 256744;
  nums[294] = 256736;
  nums[295] = 256836;
  nums[296] = 256836;
  nums[297] = 256764;
  nums[298] = 256772;
  nums[299] = 257084;
  nums[300] = 256808;
  nums[301] = 256760;
  nums[302] = 256816;
  nums[303] = 256744;
  nums[304] = 256832;
}
}
void syms_i$nit(void) 
{ 


  {
  syms[0] = 1;
  syms[1] = 3;
  syms[2] = 2;
  syms[3] = 2;
  syms[4] = 5;
  syms[5] = 5;
  syms[6] = 3;
  syms[7] = 1;
  syms[8] = 4;
  syms[9] = 1;
  syms[10] = 4;
  syms[11] = 2;
  syms[12] = 3;
  syms[13] = 1;
  syms[14] = 1;
  syms[15] = 2;
  syms[16] = 3;
  syms[17] = 2;
  syms[18] = 3;
  syms[19] = 1;
  syms[20] = 2;
  syms[21] = 3;
  syms[22] = 2;
  syms[23] = 2;
  syms[24] = 3;
  syms[25] = 1;
  syms[26] = 3;
  syms[27] = 3;
  syms[28] = 3;
  syms[29] = 5;
  syms[30] = 2;
  syms[31] = 2;
  syms[32] = 1;
  syms[33] = 2;
  syms[34] = 2;
  syms[35] = 4;
  syms[36] = 3;
  syms[37] = 1;
  syms[38] = 3;
  syms[39] = 3;
  syms[40] = 3;
  syms[41] = 5;
  syms[42] = 1;
  syms[43] = 5;
  syms[44] = 2;
  syms[45] = 2;
  syms[46] = 2;
  syms[47] = 4;
  syms[48] = 4;
  syms[49] = 1;
  syms[50] = 2;
  syms[51] = 2;
  syms[52] = 3;
  syms[53] = 4;
  syms[54] = 4;
  syms[55] = 3;
  syms[56] = 4;
  syms[57] = 2;
  syms[58] = 3;
  syms[59] = 1;
  syms[60] = 1;
}
}
void prize_encoded_i$nit(void) 
{ 


  {
  prize_encoded[0] = (char const   )-17;
  prize_encoded[1] = (char const   )29;
  prize_encoded[2] = (char const   )13;
  prize_encoded[3] = (char const   )27;
  prize_encoded[4] = (char const   )27;
  prize_encoded[5] = (char const   )-56;
  prize_encoded[6] = (char const   )31;
  prize_encoded[7] = (char const   )16;
  prize_encoded[8] = (char const   )23;
  prize_encoded[9] = (char const   )-49;
  prize_encoded[10] = (char const   )27;
  prize_encoded[11] = (char const   )-56;
  prize_encoded[12] = (char const   )31;
  prize_encoded[13] = (char const   )9;
  prize_encoded[14] = (char const   )19;
  prize_encoded[15] = (char const   )17;
  prize_encoded[16] = (char const   )22;
  prize_encoded[17] = (char const   )15;
  prize_encoded[18] = (char const   )-56;
  prize_encoded[19] = (char const   )29;
  prize_encoded[20] = (char const   )24;
  prize_encoded[21] = (char const   )-56;
  prize_encoded[22] = (char const   )23;
  prize_encoded[23] = (char const   )30;
  prize_encoded[24] = (char const   )13;
  prize_encoded[25] = (char const   )26;
  prize_encoded[26] = (char const   )-56;
  prize_encoded[27] = (char const   )16;
  prize_encoded[28] = (char const   )13;
  prize_encoded[29] = (char const   )26;
  prize_encoded[30] = (char const   )13;
  prize_encoded[31] = (char const   )-25;
  prize_encoded[32] = (char const   )-78;
  prize_encoded[33] = (char const   )-78;
  prize_encoded[34] = (char const   )1;
  prize_encoded[35] = (char const   )23;
  prize_encoded[36] = (char const   )29;
  prize_encoded[37] = (char const   )-49;
  prize_encoded[38] = (char const   )30;
  prize_encoded[39] = (char const   )13;
  prize_encoded[40] = (char const   )-56;
  prize_encoded[41] = (char const   )21;
  prize_encoded[42] = (char const   )9;
  prize_encoded[43] = (char const   )12;
  prize_encoded[44] = (char const   )13;
  prize_encoded[45] = (char const   )-56;
  prize_encoded[46] = (char const   )33;
  prize_encoded[47] = (char const   )23;
  prize_encoded[48] = (char const   )29;
  prize_encoded[49] = (char const   )26;
  prize_encoded[50] = (char const   )-56;
  prize_encoded[51] = (char const   )28;
  prize_encoded[52] = (char const   )9;
  prize_encoded[53] = (char const   )27;
  prize_encoded[54] = (char const   )19;
  prize_encoded[55] = (char const   )-44;
  prize_encoded[56] = (char const   )-56;
  prize_encoded[57] = (char const   )19;
  prize_encoded[58] = (char const   )17;
  prize_encoded[59] = (char const   )12;
  prize_encoded[60] = (char const   )-42;
  prize_encoded[61] = (char const   )-56;
  prize_encoded[62] = (char const   )-20;
  prize_encoded[63] = (char const   )17;
  prize_encoded[64] = (char const   )12;
  prize_encoded[65] = (char const   )-56;
  prize_encoded[66] = (char const   )33;
  prize_encoded[67] = (char const   )23;
  prize_encoded[68] = (char const   )29;
  prize_encoded[69] = (char const   )-56;
  prize_encoded[70] = (char const   )26;
  prize_encoded[71] = (char const   )13;
  prize_encoded[72] = (char const   )9;
  prize_encoded[73] = (char const   )20;
  prize_encoded[74] = (char const   )20;
  prize_encoded[75] = (char const   )33;
  prize_encoded[76] = (char const   )-56;
  prize_encoded[77] = (char const   )28;
  prize_encoded[78] = (char const   )16;
  prize_encoded[79] = (char const   )17;
  prize_encoded[80] = (char const   )22;
  prize_encoded[81] = (char const   )19;
  prize_encoded[82] = (char const   )-56;
  prize_encoded[83] = (char const   )33;
  prize_encoded[84] = (char const   )23;
  prize_encoded[85] = (char const   )29;
  prize_encoded[86] = (char const   )-56;
  prize_encoded[87] = (char const   )11;
  prize_encoded[88] = (char const   )9;
  prize_encoded[89] = (char const   )22;
  prize_encoded[90] = (char const   )-56;
  prize_encoded[91] = (char const   )18;
  prize_encoded[92] = (char const   )29;
  prize_encoded[93] = (char const   )27;
  prize_encoded[94] = (char const   )28;
  prize_encoded[95] = (char const   )-56;
  prize_encoded[96] = (char const   )31;
  prize_encoded[97] = (char const   )26;
  prize_encoded[98] = (char const   )17;
  prize_encoded[99] = (char const   )28;
  prize_encoded[100] = (char const   )13;
  prize_encoded[101] = (char const   )-56;
  prize_encoded[102] = (char const   )-37;
  prize_encoded[103] = (char const   )-56;
  prize_encoded[104] = (char const   )20;
  prize_encoded[105] = (char const   )17;
  prize_encoded[106] = (char const   )22;
  prize_encoded[107] = (char const   )13;
  prize_encoded[108] = (char const   )27;
  prize_encoded[109] = (char const   )-56;
  prize_encoded[110] = (char const   )23;
  prize_encoded[111] = (char const   )22;
  prize_encoded[112] = (char const   )-56;
  prize_encoded[113] = (char const   )24;
  prize_encoded[114] = (char const   )33;
  prize_encoded[115] = (char const   )28;
  prize_encoded[116] = (char const   )16;
  prize_encoded[117] = (char const   )23;
  prize_encoded[118] = (char const   )22;
  prize_encoded[119] = (char const   )-56;
  prize_encoded[120] = (char const   )9;
  prize_encoded[121] = (char const   )22;
  prize_encoded[122] = (char const   )12;
  prize_encoded[123] = (char const   )-56;
  prize_encoded[124] = (char const   )15;
  prize_encoded[125] = (char const   )13;
  prize_encoded[126] = (char const   )28;
  prize_encoded[127] = (char const   )-56;
  prize_encoded[128] = (char const   )33;
  prize_encoded[129] = (char const   )23;
  prize_encoded[130] = (char const   )29;
  prize_encoded[131] = (char const   )26;
  prize_encoded[132] = (char const   )-56;
  prize_encoded[133] = (char const   )14;
  prize_encoded[134] = (char const   )20;
  prize_encoded[135] = (char const   )9;
  prize_encoded[136] = (char const   )15;
  prize_encoded[137] = (char const   )-25;
  prize_encoded[138] = (char const   )-56;
  prize_encoded[139] = (char const   )-10;
  prize_encoded[140] = (char const   )23;
  prize_encoded[141] = (char const   )-42;
  prize_encoded[142] = (char const   )-56;
  prize_encoded[143] = (char const   )-4;
  prize_encoded[144] = (char const   )26;
  prize_encoded[145] = (char const   )29;
  prize_encoded[146] = (char const   )28;
  prize_encoded[147] = (char const   )16;
  prize_encoded[148] = (char const   )-56;
  prize_encoded[149] = (char const   )17;
  prize_encoded[150] = (char const   )27;
  prize_encoded[151] = (char const   )-42;
  prize_encoded[152] = (char const   )-42;
  prize_encoded[153] = (char const   )-42;
  prize_encoded[154] = (char const   )-56;
  prize_encoded[155] = (char const   )28;
  prize_encoded[156] = (char const   )16;
  prize_encoded[157] = (char const   )13;
  prize_encoded[158] = (char const   )-56;
  prize_encoded[159] = (char const   )15;
  prize_encoded[160] = (char const   )9;
  prize_encoded[161] = (char const   )21;
  prize_encoded[162] = (char const   )13;
  prize_encoded[163] = (char const   )-56;
  prize_encoded[164] = (char const   )31;
  prize_encoded[165] = (char const   )9;
  prize_encoded[166] = (char const   )27;
  prize_encoded[167] = (char const   )-56;
  prize_encoded[168] = (char const   )26;
  prize_encoded[169] = (char const   )17;
  prize_encoded[170] = (char const   )15;
  prize_encoded[171] = (char const   )15;
  prize_encoded[172] = (char const   )13;
  prize_encoded[173] = (char const   )12;
  prize_encoded[174] = (char const   )-56;
  prize_encoded[175] = (char const   )14;
  prize_encoded[176] = (char const   )26;
  prize_encoded[177] = (char const   )23;
  prize_encoded[178] = (char const   )21;
  prize_encoded[179] = (char const   )-56;
  prize_encoded[180] = (char const   )28;
  prize_encoded[181] = (char const   )16;
  prize_encoded[182] = (char const   )13;
  prize_encoded[183] = (char const   )-56;
  prize_encoded[184] = (char const   )27;
  prize_encoded[185] = (char const   )28;
  prize_encoded[186] = (char const   )9;
  prize_encoded[187] = (char const   )26;
  prize_encoded[188] = (char const   )28;
  prize_encoded[189] = (char const   )-42;
  prize_encoded[190] = (char const   )-56;
  prize_encoded[191] = (char const   )-17;
  prize_encoded[192] = (char const   )23;
  prize_encoded[193] = (char const   )23;
  prize_encoded[194] = (char const   )12;
  prize_encoded[195] = (char const   )10;
  prize_encoded[196] = (char const   )33;
  prize_encoded[197] = (char const   )13;
  prize_encoded[198] = (char const   )-44;
  prize_encoded[199] = (char const   )-56;
  prize_encoded[200] = (char const   )19;
  prize_encoded[201] = (char const   )17;
  prize_encoded[202] = (char const   )12;
  prize_encoded[203] = (char const   )-42;
}
}
void gameRun(void) 
{ 
  char command ;
  int userNumber ;
  unsigned int r4ndNumber ;
  unsigned int tmp ;
  char a ;

  {
  command = (char)0;
  userNumber = 0;
  r4ndNumber = 0U;
  seed = 4208904958U;
  printf((char const   */* __restrict  */)"I will give you secret for 200 c01n5 - no more, no less. Exactly 200. You see 200 - you leave casino. To do this, you must beat THE RANDOM\n");
  while (1) {
    if (m0n3y > 0) {
      if (! (m0n3y < 200)) {
        break;
      }
    } else {
      break;
    }
    printTurn();
    scanf((char const   */* __restrict  */)"%1s", & command);
    if ((int )command == 112) {
      printf((char const   */* __restrict  */)"[?] Now provide number from 0 to 9: ");
      scanf((char const   */* __restrict  */)"%1d", & userNumber);
      userNumber %= 10;
      tmp = r4nd0m(seed);
      seed = tmp % 10U;
      r4ndNumber = seed;
      if ((unsigned int )userNumber == r4ndNumber) {
        m0n3y += 10;
        printf((char const   */* __restrict  */)"\n[+] You won!\n\n");
      } else {
        m0n3y -= 10;
        printf((char const   */* __restrict  */)"\n[-] You lost!\n\n");
      }
    } else
    if ((int )command == 115) {
      printf((char const   */* __restrict  */)"\n[.] Ok, goodbye!\n");
      break;
    } else {
      printf((char const   */* __restrict  */)"[x] Unknown command!\n");
    }
  }
  if (m0n3y == 200) {
    printf((char const   */* __restrict  */)"Wow! Now you have enough m0n3y to buy s3cr37!!! To get it, please, give me last number you entered:");
    a = (char)0;
    scanf((char const   */* __restrict  */)"%1d", & a);
    printf((char const   */* __restrict  */)"\n");
    printPrize((char )((int )a + 80));
  } else {
    printf((char const   */* __restrict  */)"[$] You have %d c01n5\n", m0n3y);
  }
  return;
}
}
void __attribute__((__optimize__(3)))  printPrize(char a ) 
{ 
  size_t i ;

  {
  i = (size_t )0;
  while (i < (size_t )prizeLength) {
    printf((char const   */* __restrict  */)"%c", (int )a + (int )prize_encoded[i]);
    i ++;
  }
  printf((char const   */* __restrict  */)"\n");
  return;
}
}
void m0n3y_i$nit(void) 
{ 


  {
  m0n3y = 100;
}
}
void printBanner(void) 
{ 


  {
  printf((char const   */* __restrict  */)"####################################\n#                                  #\n#       Welcome to the c451n0!     #\n#                                  #\n####################################\n");
  return;
}
}
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) 
{ 
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = _formal_argc;
  _global_argv = _formal_argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  printBanner();
  gameRun();
  return (0);
}
}
void prizeLength_i$nit(void) 
{ 


  {
  prizeLength = (int const   )204;
}
}
void numsLength_i$nit(void) 
{ 


  {
  numsLength = 305;
}
}
void xorKey_i$nit(void) 
{ 


  {
  xorKey = 64206;
}
}
void megaInit(void) 
{ 


  {
  nums_i$nit();
  prizeLength_i$nit();
  prize_encoded_i$nit();
  syms_i$nit();
  m0n3y_i$nit();
  numsLength_i$nit();
  seed_i$nit();
  xorKey_i$nit();
}
}
void __attribute__((__optimize__(3)))  pr0c(void) 
{ 
  char _1_pr0c_$locals[40] ;
  union _1_pr0c_$node _1_pr0c_$stack[1][32] ;
  union _1_pr0c_$node *_1_pr0c_$sp[1] ;
  unsigned char *_1_pr0c_$pc[1] ;

  {
  _1_pr0c_$sp[0] = _1_pr0c_$stack[0];
  _1_pr0c_$pc[0] = _1_pr0c_$array[0];
  while (1) {
    switch (*(_1_pr0c_$pc[0])) {
    case _1_pr0c__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + -1)->_int = (_1_pr0c_$sp[0] + -1)->_int + (_1_pr0c_$sp[0] + 0)->_int;
    (_1_pr0c_$sp[0]) --;
    break;
    case _1_pr0c__BXor_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + -1)->_int = (_1_pr0c_$sp[0] + -1)->_int ^ (_1_pr0c_$sp[0] + 0)->_int;
    (_1_pr0c_$sp[0]) --;
    break;
    case _1_pr0c__convert_char2int$left_STA_0$result_STA_0: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + 0)->_int = (int )(_1_pr0c_$sp[0] + 0)->_char;
    break;
    case _1_pr0c__global$result_STA_0$value_LIT_0: 
    (_1_pr0c_$pc[0]) ++;
    switch (*((int *)_1_pr0c_$pc[0])) {
    case 2: 
    (_1_pr0c_$sp[0] + 1)->_void_star = (void *)(nums);
    break;
    case 0: 
    (_1_pr0c_$sp[0] + 1)->_void_star = (void *)(syms);
    break;
    case 1: 
    (_1_pr0c_$sp[0] + 1)->_void_star = (void *)(& numsLength);
    break;
    case 3: 
    (_1_pr0c_$sp[0] + 1)->_void_star = (void *)(& xorKey);
    break;
    }
    (_1_pr0c_$sp[0]) ++;
    _1_pr0c_$pc[0] += 4;
    break;
    case _1_pr0c__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + -1)->_unsigned_long = (_1_pr0c_$sp[0] + 0)->_unsigned_long * (_1_pr0c_$sp[0] + -1)->_unsigned_long;
    (_1_pr0c_$sp[0]) --;
    break;
    case _1_pr0c__convert_void_star2void_star$left_STA_0$result_STA_0: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + 0)->_void_star = (_1_pr0c_$sp[0] + 0)->_void_star;
    break;
    case _1_pr0c__constant_int$result_STA_0$value_LIT_0: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + 1)->_int = *((int *)_1_pr0c_$pc[0]);
    (_1_pr0c_$sp[0]) ++;
    _1_pr0c_$pc[0] += 4;
    break;
    case _1_pr0c__call$func_LIT_0: 
    (_1_pr0c_$pc[0]) ++;
    switch (*((int *)_1_pr0c_$pc[0])) {
    case 1: 
    printf(*((char const   * __restrict  *)(_1_pr0c_$locals + 16)), *((int *)(_1_pr0c_$locals + 24)));
    break;
    case 2: 
    printf(*((char const   * __restrict  *)(_1_pr0c_$locals + 32)));
    break;
    }
    _1_pr0c_$pc[0] += 4;
    break;
    case _1_pr0c__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + -1)->_int = (_1_pr0c_$sp[0] + 0)->_int < (_1_pr0c_$sp[0] + -1)->_int;
    (_1_pr0c_$sp[0]) --;
    break;
    case _1_pr0c__string$result_STA_0$value_LIT_0: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + 1)->_void_star = (void *)(_1_pr0c_$strings + *((int *)_1_pr0c_$pc[0]));
    (_1_pr0c_$sp[0]) ++;
    _1_pr0c_$pc[0] += 4;
    break;
    case _1_pr0c__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_pr0c_$pc[0]) ++;
    if ((_1_pr0c_$sp[0] + 0)->_int) {
      _1_pr0c_$pc[0] += *((int *)_1_pr0c_$pc[0]);
    } else {
      _1_pr0c_$pc[0] += 4;
    }
    (_1_pr0c_$sp[0]) --;
    break;
    case _1_pr0c__load_int$left_STA_0$result_STA_0: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + 0)->_int = *((int *)(_1_pr0c_$sp[0] + 0)->_void_star);
    break;
    case _1_pr0c__convert_int2unsigned_long$left_STA_0$result_STA_0: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_pr0c_$sp[0] + 0)->_int;
    break;
    case _1_pr0c__returnVoid$: 
    (_1_pr0c_$pc[0]) ++;
    return;
    break;
    case _1_pr0c__local$result_STA_0$value_LIT_0: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + 1)->_void_star = (void *)(_1_pr0c_$locals + *((int *)_1_pr0c_$pc[0]));
    (_1_pr0c_$sp[0]) ++;
    _1_pr0c_$pc[0] += 4;
    break;
    case _1_pr0c__constant_unsigned_long$result_STA_0$value_LIT_0: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_pr0c_$pc[0]);
    (_1_pr0c_$sp[0]) ++;
    _1_pr0c_$pc[0] += 8;
    break;
    case _1_pr0c__Div_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + -1)->_int = (_1_pr0c_$sp[0] + 0)->_int / (_1_pr0c_$sp[0] + -1)->_int;
    (_1_pr0c_$sp[0]) --;
    break;
    case _1_pr0c__MinusA_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + -1)->_int = (_1_pr0c_$sp[0] + -1)->_int - (_1_pr0c_$sp[0] + 0)->_int;
    (_1_pr0c_$sp[0]) --;
    break;
    case _1_pr0c__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + -1)->_void_star = (_1_pr0c_$sp[0] + -1)->_void_star + (_1_pr0c_$sp[0] + 0)->_int;
    (_1_pr0c_$sp[0]) --;
    break;
    case _1_pr0c__store_void_star$left_STA_0$right_STA_1: 
    (_1_pr0c_$pc[0]) ++;
    *((void **)(_1_pr0c_$sp[0] + 0)->_void_star) = (_1_pr0c_$sp[0] + -1)->_void_star;
    _1_pr0c_$sp[0] += -2;
    break;
    case _1_pr0c__PlusPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + -1)->_void_star = (_1_pr0c_$sp[0] + -1)->_void_star + (_1_pr0c_$sp[0] + 0)->_unsigned_long;
    (_1_pr0c_$sp[0]) --;
    break;
    case _1_pr0c__Eq_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + -1)->_int = (_1_pr0c_$sp[0] + -1)->_int == (_1_pr0c_$sp[0] + 0)->_int;
    (_1_pr0c_$sp[0]) --;
    break;
    case _1_pr0c__constant_void_star$result_STA_0$value_LIT_0: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + 1)->_void_star = *((void **)_1_pr0c_$pc[0]);
    (_1_pr0c_$sp[0]) ++;
    _1_pr0c_$pc[0] += 8;
    break;
    case _1_pr0c__convert_int2char$left_STA_0$result_STA_0: 
    (_1_pr0c_$pc[0]) ++;
    (_1_pr0c_$sp[0] + 0)->_char = (char )(_1_pr0c_$sp[0] + 0)->_int;
    break;
    case _1_pr0c__store_int$left_STA_0$right_STA_1: 
    (_1_pr0c_$pc[0]) ++;
    *((int *)(_1_pr0c_$sp[0] + 0)->_void_star) = (_1_pr0c_$sp[0] + -1)->_int;
    _1_pr0c_$sp[0] += -2;
    break;
    case _1_pr0c__goto$label_LAB_0: 
    (_1_pr0c_$pc[0]) ++;
    _1_pr0c_$pc[0] += *((int *)_1_pr0c_$pc[0]);
    break;
    }
  }
}
}
void seed_i$nit(void) 
{ 


  {

}
}
unsigned int r4nd0m(unsigned int prev ) 
{ 


  {
  return (prev * 1664523U + 1013904227U);
}
}
void printTurn(void) 
{ 


  {
  printf((char const   */* __restrict  */)"[$] Current balance: %d c01n5\n", m0n3y);
  printf((char const   */* __restrict  */)" What do you wanna do?\n  1) Play game for 10 c01n5 - press p\n  2) Stop playing - press s\n[@]> ");
  return;
}
}
