version: '2.3'

services:
  task:
    build: src
    restart: always
    ports:
      - 35004:25004
    pids_limit: 512
    mem_limit: 128M
    privileged: true
    volumes:
      - ./src/nsjail/logs/:/var/log/nsjail/

networks:
  default:
    external:
      name: my-docker-net
